### ISSUE TITLE
I am not able to register any block into the game

### ISSUE THREAD

**Issue by GalaxyRuler1234** [Tutorials-By-Kaupenjoe/Forge-Tutorial-1.18.1#9]
I am not able to register any block into the game @Kaupenjoe

**Comment by Kaupenjoe** [comment]
@GalaxyRuler1234 Make a public GitHub Repo and I'll take a look at it.

**Comment by Treeways** [comment]
Hi @Kaupenjoe! Great tutorial so far, but I'm having the same issue. I tried adding a block to the game, but it doesn't seem to properly register in the game at all.

I'm pretty sure I copied the code you showed in the video exactly to the point [where you added the Citrine Block.](https://www.youtube.com/watch?v=c2zgZI5iTwo&list=PLKGarocXCE1Hut51TKKqZKqVZtKLZC48x&index=4)

Here's my code repository: https://github.com/Treeway7/Blockchain

**Comment by Treeways** [comment]
Just had a little look around and it looks like the block itself is registered fine (I tried /setblock and it worked), but from the code in the video it looks like the block's item isn't being registered properly for some reason.

(EDIT: It's evident that it's the item not registering rather than a creative mode item issue because trying to find the block in /give doesn't show up with my mod's ID.)

**Comment by Treeways** [comment]
So it looks like I missed this because I sped through the ModItems tutorial, so make sure to actually register the items (and blocks) in the mod's constructor!

See lines 35 and 36:

https://github.com/Tutorials-By-Kaupenjoe/Forge-Tutorial-1.18.1/blob/4-blocks/src/main/java/net/kaupenjoe/tutorialmod/TutorialMod.java#L35
